### ISSUE TITLE
PDF minicon too small?

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#274] opened 2015-02-03 19:38 UTC
When used at 16 px to designate a PDF resource next to a link, the PDF minicon is so tiny, it's difficult to read. Should we reconsider the design? Or, the specs for sizing?

From [Owning a Home:](http://www.consumerfinance.gov/owning-a-home/)
![screen shot 2015-02-03 at 2 36 24 pm](https://cloud.githubusercontent.com/assets/6223901/6027740/1f122e84-abb2-11e4-941b-918b941e8a0b.png)

**Comment by Dnpizarro** [comment] 2015-02-03 23:14
@mebates you have a point. The letters on the minicon are completely unreadable. This is going to need a revision.

**Comment by Dnpizarro** [comment] 2015-02-03 23:16
@ohsk this brings to mind why The Noun Project flagged some of our minicons and it was because we had text on them. With this in mind, I think we would have to reconsider any minicons that have text/letters as part of their design.

**Comment by jimmynotjim** [comment] 2015-02-04 01:43
Have you considered redrawing the icons for specific sizes? [Iconic does this](https://useiconic.com/guides/how-to-use-the-icon-font/) with their icon font, not sure how difficult it is to package multiple sizes through Font Squirrel but nearly every font does this with hinting.

**Comment by Dnpizarro** [comment] 2015-02-04 15:22
@jimmynotjim we considered that at some point, but didn't really find enough good use cases for having different designs for for specific sizes. But to touch on that point, we have a 3 tier system that starts with our minicons > iscons > illustrations. Each level up has a relationship to scale and hierarchy of content. For example we use our illustration style for top level headers were as we rely on our minicons as UI elements.

**Comment by stephanieosan** [comment] 2015-02-04 19:51
Even if we scaled up the minicon in relation to the link, I still don't think it's very legible:
![screen shot 2015-02-04 at 2 52 50 pm](https://cloud.githubusercontent.com/assets/6433178/6048340/849489ac-ac7d-11e4-92ac-8d3cd636b54e.png)

I lean toward redesigning it. Does it need to say "PDF"? What if it had an arrow inside the page to show that it was a download?

**Comment by Dnpizarro** [comment] 2015-02-04 20:05
That minicon already exists, its the download minicon:

![screen shot 2015-02-04 at 3 04 49 pm](https://cloud.githubusercontent.com/assets/6852363/6048567/31a2d6d4-ac7f-11e4-933a-00ab96d98a2c.png)

**Comment by stephanieosan** [comment] 2015-02-04 20:10
Ah, good point. Maybe we just use that and eliminate the PDF-specific minicon?

**Comment by mebates** [comment] 2015-02-04 20:21
I think that's a reasonable (and easy) solution, @stephanieosan.

**Comment by Dnpizarro** [comment] 2015-02-04 21:34
I agree. +1

**Comment by mebates** [comment] 2015-02-17 20:48
Hey @Dnpizarro - in order to close this out, should the icon be removed from the Design Manual and the minicon font?

**Comment by Dnpizarro** [comment] 2015-02-17 22:40
Good point! I'll reopen it and I'll close it out again once its updated.

**Comment by mebates** [comment] 2015-08-11 21:18
Working with @danny8000 on pages today and noticed that the PDF icon is still in the Design Manual and minicon font. @Dnpizarro - is this geared up to be removed from the font? I think I can figure out how to remove it from the DM.

**Comment by klocraft** [comment] 2015-08-12 13:12
This question may focus too much on semantics, but when consumers click a PDF link on our website, are they actually downloading the PDF? Or is the PDF just opening in a browser? A 'download' minicon could be misleading.

**Comment by Scotchester** [comment] 2015-08-12 14:15
@mebates I'm not sure it warrants removing it entirely. Could still be useful if we ever use minicons at larger-than-body-copy sizes. Also, removing it could break existing uses of it, unless we replace that same character code with a duplicate of the standard download icon.

Unless we want to make sure no one ever uses the icon for anything ever again, I say just leave it in and publicize the guidance to not use it in conjunction with body-sized links.

**Comment by ohsk** [comment] 2015-08-12 16:15
Sorry if this is side-tracking our current convo, but I'd like to propose updating the download icon, or creating a separate download icon than our current version, which I think more specifically relates to "downloading a document"

![image](https://cloud.githubusercontent.com/assets/1689222/9229534/96edcc82-40eb-11e5-9843-c69763d4a3e5.png)

Something like the options to the right seems generally more scalable, and more broadly relates to some of our use cases of download datasets in .csv or .xls.

**Comment by mebates** [comment] 2015-08-21 19:05
I like this @ohsk. @Dnpizarro - what do you think of this update?

@klocraft makes a fair point that the web behavior is usually that the PDF opens in a new window, then you have the ability to download it. Should we get more specific about how to signify that?

I'm not sure that leaving the PDF icon in the Design Manual is necessary; we can leave it in the font but don't want it mistakenly used at 16 px (most common use) by people going forward. I'm going to remove it from the Design Manual for now and we can leave it in the font.

**Comment by Dnpizarro** [comment] 2015-08-31 13:43
@ohsk I like you suggestions with the larger arrow. It definitely scales much better than the options with the document. If I had to pick, I like the arrow with the rounded rule line. 

About the point that @klocraft made, I think this is a UX question. With that said, if we decide to go with opening up the pdf in a new window then we should avoid using the download minicon.

**Comment by Scotchester** [comment] 2015-08-31 14:21
It was decided in #294 to _not_ open PDFs in new windows.

**Comment by Dnpizarro** [comment] 2015-09-01 13:13
Thanks @Scotchester for answering that. @ohsk do you think you can mock up an example of the suggested changes you proposed?

**Comment by ohsk** [comment] 2015-09-09 13:14
Hey folks, sorry for the delay. Just getting back into the swing of things this week.
Take a look at this set and let me know if you have any thoughts! 
It's the rounded-line version from [this iteration](https://github.com/cfpb/design-manual/issues/274#issuecomment-130359052).

![minicon_download_v1](https://cloud.githubusercontent.com/assets/1689222/9762703/325a6a0c-56d3-11e5-9107-f297adcfec88.png)

**Comment by danny8000** [comment] 2015-09-14 14:01
Have we considered the Acrobat logo:

http://fortawesome.github.io/Font-Awesome/icon/file-pdf-o/

![acrobat-icon](https://cloud.githubusercontent.com/assets/2364420/9851598/76e6d424-5ac7-11e5-820c-5aa22eef5850.png)

Not sure if this would create copyright issues, but it is readable at small sizes, and it is recognizable as a PDF -- the download icon is generic to any kind of downloadable file.

If we use the download icon, should there be additional text identifying the link as a PDF, e.g.:

<a href="http://files.consumerfinance.gov/f/201503_cfpb_your-home-loan-toolkit-web.pdf">Home loan toolkit [pdf]</a>

**Comment by Dnpizarro** [comment] 2015-09-16 13:46
@danny8000 you bring up a good point! I guess a couple of points/questions come to mind. If we take the direction of adding a label [pdf], we would probably have to do this for all other files types (e.i. pdf, excel, word, csv, etc). So something like: Title of file [file type]

How important is it for us to label the downloadable file? Alternatively, I feel this can potentially be solved through an editorial approach. The example below is from the Realtor's Guide.

<img width="660" alt="screen shot 2015-09-16 at 9 42 24 am" src="https://cloud.githubusercontent.com/assets/6852363/9906265/672c4050-5c57-11e5-9bdf-874465748996.png">

**Comment by KimberlyMunoz** [comment] 2015-09-16 18:12
> Alternatively, I feel this potentially be solved through an editorial approach.

I agree. The icons are good visual indicators of pdfs and downloadable content, but they shouldn't be the only ones. Screenreaders and older browsers that struggle with icon fonts might not be able to read them, but they should still get the context they need.

**Comment by nataliafitzgerald** [comment] 2015-10-22 16:07
@ohsk - Can you post a visual layout of this at different sizes with sample labels, rather than the pixels sizes text?

**Comment by ohsk** [comment] 2015-10-22 17:59
@nataliafitzgerald Let me know if this helps!

![download_examples](https://cloud.githubusercontent.com/assets/1689222/10673698/2916b752-78c5-11e5-96a6-619ffa165e2a.png)

**Comment by stephanieosan** [comment] 2016-12-20 21:54
Do the designers want to continue to pursue this?

**Comment by caheberer** [comment] 2017-01-23 18:45
We've made a decision not to use the PDF icon anymore. 

Next steps:
- Remove PDF icon from minicon font

**Closed as completed by caheberer** 2017-01-23 18:45 UTC
Labels: Discuss in meeting
