### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by jehlers** [cfpb/design-manual#233] opened 2014-06-30 17:05 UTC
Right now, Owning a Home is using these tabs to show different content for 2 different use cases/user scenarios: 

![screen shot 2014-06-30 at 1 01 27 pm](https://cloud.githubusercontent.com/assets/4267825/3432790/87c94af6-0078-11e4-9b62-957e5ffee5ad.png)

@iuloshi can you post the tabs that you are planning to use for Consumer Response?

Anyone else have tabs we should discuss so we can find a consistent brand pattern?

**Comment by mebates** [comment] 2014-06-30 17:49
Intranet:
![screen shot 2014-06-30 at 1 48 36 pm](https://cloud.githubusercontent.com/assets/6223901/3433362/d5318dca-007e-11e4-8fa2-3d34df97c5a0.png)

**Comment by iuloshi** [comment] 2014-07-01 20:43
Initial Consumer Complaint Database data viz tabs:

![screen shot 2014-07-01 at 4 44 14 pm](https://cloud.githubusercontent.com/assets/1676307/3449000/7e61cf36-0160-11e4-977c-191cd1707603.png)

**Comment by mebates** [comment] 2014-08-26 15:14
@sephcoster and @dezzie are building tabs into the HMDA 2013 release and we're not sure where to go visually. @danny8000 began developing a capital framework version of tabs that looks pretty close to the Intranet, but I don't think that's the direction we're heading on cf.gov. @duelj and @ell0ell0, have any examples come up in your designs?

**Comment by sephcoster** [comment] 2014-08-26 17:26
Example tab set from HMDA - using HMDA gold100 active and gold80 hover. This code uses @danny8000's code as a baseline as it's 508 compliant and support keyboard / voice nav. Still a work in progress - providing as an example:
![screen shot 2014-08-26 at 1 24 43 pm](https://cloud.githubusercontent.com/assets/1028659/4048679/051517ac-2d46-11e4-9cd8-9b8df812d306.png)

**Comment by Dnpizarro** [comment] 2014-11-14 15:44
@himedlooff good work on this! If you haven't checked out the [tabs demo](http://himedlooff.github.io/cf-tabs/demo/), please do. 

I'm going to queue this issue up at Monday's Design Manual Review meeting. If anyone has any additional ideas they want to add, please add them to this thread and we can discuss them further on Monday.

**Comment by himedlooff** [comment] 2014-11-14 16:10
So this code is something @danny8000 started. I was just trying to port it to a more Capital Framework friendly format. This also means I'm not sure where the design came from and what inspired it.

**Comment by nataliafitzgerald** [comment] 2014-11-14 21:59
It feels as through this issue may require further exploration before we make a call particularly with our consumer facing products. I'm interested to see whether flapjack has a need for tabs and if so, what their approach is. @mebates confirmed that Owning a Home has tabs coming up in the Rate Checker release.

**Comment by himedlooff** [comment] 2014-11-17 14:15
Flapjack has not needed tabs yet.

**Comment by stephanieosan** [comment] 2014-11-17 15:40
Yes, the tabs we have coming up are the ones @jehlers posted at the very top of the issue.

**Comment by stephanieosan** [comment] 2014-11-17 19:19
During the design manual review meeting today we discussed a smaller-sized version of the tabs used in  owning a home. Here's my first pass at them. I still need to do a little thinking about how these would translate to mobile. 

![screen shot 2014-11-17 at 2 17 26 pm](https://cloud.githubusercontent.com/assets/6433178/5075884/a48e154a-6e64-11e4-8c74-d59a26bf35c0.png)

**Comment by himedlooff** [comment] 2014-11-17 19:41
I've seen some that stack on mobile like this:

![image](https://cloud.githubusercontent.com/assets/1093373/5076268/c38635e2-6e67-11e4-9c94-e87e53333b84.png)

**Comment by Dnpizarro** [comment] 2014-12-02 15:36
Those look good @stephanieosan . For mobile, I think @himedlooff has a nice solution above. If we apply the styling @stephanieosan has in her mockups, the delineation between tabs will be more evident.

**Comment by stephanieosan** [comment] 2014-12-02 15:41
I can take a stab at applying the styling to @himedlooff's mobile recommendation.

**Comment by stephanieosan** [comment] 2014-12-02 15:48
![screen shot 2014-12-02 at 10 48 26 am](https://cloud.githubusercontent.com/assets/6433178/5265489/cfbf7030-7a10-11e4-80ff-f03f03588ba3.png)

**Comment by Dnpizarro** [comment] 2014-12-02 16:44
@stephanieosan these tabs look nice! I'm wondering if the full span of dotted line button is even necessary. I feel like  the dotted line button is creating a visual break, that is also full width, causing a bit on conflict with the tabs. Maybe if the dotted lines are removed it will be more clear that the content is all part of that first tab.

**Comment by Scotchester** [comment] 2014-12-02 16:46
The dotted-lined-full-width links are our standard way of making those standalone-type links more finger-friendly on mobile devices. I would recommend against making an exception for when they're used in a tab set.

**Comment by duelj** [comment] 2014-12-02 17:04
I like the tab style for mobile as well. My first thought was how do these tabs differ from the expand collapse accordions when it comes to mobile? FJ has used the accordions for mobile to show some table content on smaller screens and it seems like the interaction of these tabs would work. If the interaction is the same just wondered if we needed both styles? As it stand the accordion has an expand minicon. 
![screen shot 2014-12-02 at 12 01 32 pm](https://cloud.githubusercontent.com/assets/6873734/5266958/474f1e0c-7a1b-11e4-8c18-719d8af84981.png)
![screen shot 2014-12-02 at 12 03 03 pm](https://cloud.githubusercontent.com/assets/6873734/5266959/4a7d3ca8-7a1b-11e4-94d7-732b708f8fd0.png)

**Comment by himedlooff** [comment] 2014-12-02 17:14
@duelj, so true, tabs could convert to accordions on mobile.

**Comment by Dnpizarro** [comment] 2014-12-02 17:23
Good point @duelj . Not much of a difference for mobile, but I guess the question then becomes how does the styling of the "tab" in @stephanieosan case change for desktop.

**Comment by himedlooff** [comment] 2014-12-02 17:29
It doesn't have to change. Unless I'm missing something.

**Comment by himedlooff** [comment] 2014-12-02 17:33
We can use tabs on large screens and switch it to a full-on expandable on small screens, or on small screens we just use some code from expandables to do the expanding stuff and keep the same tab-like style throughout the experience.

**Comment by duelj** [comment] 2014-12-02 17:41
+1 @himedlooff 
Sounds pretty snazzy to me.

**Comment by Dnpizarro** [comment] 2014-12-02 17:46
@himedlooff functionally the expandable solution is a good one. I was referring to how we would resolve the visual treatment for the large screens based on the mobile treatment @duelj showed because the midtone green bar plays a strong role is distinguishing between show and hide in @stephanieosan mockups.

**Comment by himedlooff** [comment] 2014-12-02 18:04
We could keep the large screen styles as @stephanieosan has them and on small screens style them as expandables. I don't think it matters that they don't look the same from small to large as long as people know that they can toggle content on and off. A user will most likely see one or the other, not both.

**Comment by caheberer** [comment] 2015-02-02 20:49
I’m currently designing for a similar use and thought I would weigh in on this…

Originally I felt that the green line for the onstate was fussy, but I’m feeling in agreement now for the following reasons:
- It works on a white background which is essential for middle of page uses (when you can’t have a colored background to define the white tab shape like in the Consumer Complaint Database example)
- If you use a solid color versus the bar, it makes it look less like a tab
- It emphasizes which tab is open when on mobile

The only thing that I wonder is if on large screens we need the gray bar for the inactive tabs? I think it’s a tiny bit cleaner to remove it. (Especially in instances when there’s a minicon involved)
![screen shot 2015-02-02 at 3 45 59 pm](https://cloud.githubusercontent.com/assets/4739887/6008902/0f40aba8-aaf3-11e4-8e59-3630516515d0.png)

**Comment by Dnpizarro** [comment] 2015-02-04 21:53
@caheberer if the tabs aren't greyed out, is there going to be any kind of a visual cue to suggest that the tabs are inactive? Maybe if the minicon and text in the inactive tab are greyed out instead, but not sure if that would look good.

**Comment by caheberer** [comment] 2015-02-16 20:12
@Dnpizarro totally agree with what you're saying, greying out the tab while inactive is essential, I was only referring to the thin line on top. (I circled it in red in the screenshot) Maybe not necessary? 

![screen shot 2015-02-16 at 3 10 25 pm](https://cloud.githubusercontent.com/assets/4739887/6218632/20ced40c-b5ee-11e4-8581-d82e0b8891b5.png)

**Comment by duelj** [comment] 2015-02-18 18:34
Yea, I think getting rid of the top bar is nice, Maybe have it appear on hover or as a focus state. Basically the same as the Google gmail interaction for tabs: 
![screen shot 2015-02-18 at 1 33 19 pm](https://cloud.githubusercontent.com/assets/6873734/6253918/dcf33472-b772-11e4-96e7-60dfa4072483.png)

**Comment by Dnpizarro** [comment] 2015-02-18 20:30
Yeah I agree. The google gmail example looks really nice.

**Comment by nataliafitzgerald** [comment] 2015-02-20 20:11
The Google example has thin rule lines around the inactive tabs. Perhaps we can explore an option that removes the thick gray bar but includes 1 px gray lines to frame the inactive tabs?

**Comment by caheberer** [comment] 2015-02-24 15:57
I think gray inactive tabs are easier for users to understand than all white. I do see that there is a very thin rule on the Google example, but would still argue it's unnecessary, but if it's as thin as that it's less distracting. Agree with @duelj that the thicker line can appear as hover / focus.

**Comment by caheberer** [comment] 2015-06-23 16:46
I tried to consolidate all of our comments into this iteration. I’m following the (brilliant) idea to use expandables on medium and small screens. The first image shows the design in full, the following shows it in the design manual template.

Let me know what you guys think and if we are ready to request final design approval from Natalia.

![screen shot 2015-06-23 at 12 40 48 pm](https://cloud.githubusercontent.com/assets/4739887/8311614/6dcb53f0-19a5-11e5-9b5f-bc5e0e230f9a.png)

![ui-designmanual_tabs_tabs-01](https://cloud.githubusercontent.com/assets/4739887/8311616/71e50bf2-19a5-11e5-8baf-a6598c1bdc4b.png)

**Comment by mebates** [comment] 2015-06-23 21:07
This is nice. At first I wondered why you detailed out active/hover/inactive state for the minicon variation, but then I saw the tooltip on Hover. Does that standard sync up with our work on #139?

**Comment by caheberer** [comment] 2015-06-23 21:18
Yeah, I'd be happy to make that a standard tooltip style, but there isn't consensus on #139  Aaah! 

It's also slightly different from a tooltip, considering it needs to follow the hover state, so if the decided upon tooltip doesn't have a white background with black type it's not going to work. It seems like folks were gravitating towards Gray 5% background, 1px Gray 50% border, black type for the tooltip, but if we went with white it could be the same. Thoughts @mebates?

We could try to close out both issues this sprint?

**Comment by duelj** [comment] 2015-06-24 19:41
#### Sorry I am late to the game but I had a couple of questions about the tabs
- How would a user on a touch device know what the minicon tabs stood for? 
  - I am guessing the active tab title is to help with this, but I only see examples of it with the further left tab selected. I am curious how it looks with a middle or right tab selected (its the label always far left or is it centered below?)
- How do tabs work on mobile? Are there situations where a large screen format tab changes to a minicon tab at mobile width screens? 
- Are there any guidelines being developed around tab use cases? The stylistic guidelines are good but it seems like it is a concern if more teams begin trying to use tabs as an auxiliary means of navigation within the site (vs. navigating between panels of content within the content area of a page) OAH and KBYO Real Estate Guide are examples of tabs as navigation. Examples [Real Estate Guide](https://github.cfpb.gov/design-ops/kbyo-launch/issues/4#issuecomment-47527), [OAH Know the Process](http://build.consumerfinance.gov/owning-a-home/process/prepare/)

**Comment by caheberer** [comment] 2015-06-24 20:16
Welcome to the game!

On a touch device (both medium and small screens) they would follow expandable styling, so the name of each tab would be next to the icon, like this:
![screen shot 2015-06-24 at 4 14 52 pm](https://cloud.githubusercontent.com/assets/4739887/8340385/29e683de-1a8c-11e5-8230-64c70a769e93.png)

I'm not proposing the tabs in this issue be used in instances like the Real Estate Guide or OAH Know the Process. I agree with the comments you made on those issues in that they should follow the new flapjack navigation standards. Not sure how others feel...

**Comment by duelj** [comment] 2015-06-25 14:37
Nice! Thanks for sharing that stuff, I just wasn't sure since I didn't see the mobile stuff on the DM page. As for the tab navigation stuff I [started an issue](https://github.com/cfpb/design-manual/issues/328) to have on the backlog in case that needs to be discussed more in the future.

**Comment by elizbond** [comment] 2015-07-29 18:57
@Dnpizarro and @keelerr will take this over for Design Ops.

**Comment by Dnpizarro** [comment] 2015-08-11 13:43
@caheberer I was curious to know what the UX justification was for hiding the tab label? I know there has been some discussion about this in previous Friday presentations, and was wondering if the UX perspective has been documented anywhere. @keelerr started a [working google doc](https://docs.google.com/document/d/1m1UIb_DplE7i719rwozFb6vVGmOmyLwYFkmYMNyazAc/edit) to capture thoughts and feedback.

**Comment by caheberer** [comment] 2015-08-11 13:57
@Dnpizarro do you mean in the variation? With the icons?

If space allows, it is preferred to include the label, even if using an icon. I'm now seeing in the design manual page that I wrote, that is not readily apparent. 

In the case presented for the variation, the titles of each were too long to fit, but a use case was still needed for wanting to expose multiple categories of equal prominence, which could only be achieved by the horizontal arrangement. (Expandables were originally presented as an option for the desktop version as well, but the "open" item pushes the other categories down too far and the other categories weren't visible to the user.)

Did that help? Let me know if you have further questions.

**Comment by Dnpizarro** [comment] 2015-08-12 19:56
@caheberer that makes sense. Spacing can definitely be an issue with long labels, particularly in your use case. Generally, I'm trying to get a broader understanding of how to best deal with tab labels because they tend to get long at times. By any chance has your team done any user testing on these tabs?

**Comment by caheberer** [comment] 2015-08-12 20:05
@Dnpizarro sadly no, and it doesn't sound like it's in the immediate future.

**Comment by stephanieosan** [comment] 2016-12-20 21:32
@caheberer We need an update on the status of tabs! It seems like you have a design manual page built for it...locally? 

Are there open questions that need to get figured out on this before we can submit a PR for it?

**Comment by stephanieosan** [comment] 2016-12-20 21:34
Closing this issue, moving forward this will be where all the Tab chat happens:
https://github.com/cfpb/design-manual/issues/352

**Closed as completed by stephanieosan** 2016-12-20 21:34 UTC
Labels: 1 - Working
