### ISSUE TITLE
8px margin around body

### ISSUE THREAD

**Issue by iuloshi** [cfpb/design-manual#92] opened 2014-03-31 17:55 UTC
I'm checking out the Design Manual in Chrome and it looks like we have that 8px margin around the body again. 

I compared [this pull request](https://github.com/Scotchester/design-manual/commit/64c4e3acf4b88df7660bb57f05de7fc5dfe5fe27) to the current code and they are consistent. Is it still not importing `normalize.css` correctly? 

@Scotchester Would you mind taking a look when you have a minute, since you resolved this issue the last time? Thanks!

**Comment by Scotchester** [comment] 2014-03-31 21:01
I screwed this up, actually. I had an old version of Normalize on my local install with an incorrect path. The linked PR will fix it for future builds.

**Comment by iuloshi** [comment] 2014-04-01 20:31
Still looks like it's there? :/

![screen shot 2014-04-01 at 4 31 03 pm](https://cloud.githubusercontent.com/assets/1676307/2584282/9aed9746-b9dc-11e3-8c9b-768f96dc1b90.png)

**Comment by Scotchester** [comment] 2014-04-01 20:42
No one has rebuilt the CSS since my PR was merged. In hindsight, I probably should have done it along with the root cause fix that I implemented.

**Comment by iuloshi** [comment] 2014-04-01 21:35
Gotcha. My last PR has lots of LESS updates!

**Comment by Scotchester** [comment] 2014-04-04 21:10
Think this is finally licked!

**Closed as completed by Scotchester** 2014-04-04 21:10 UTC

**Comment by iuloshi** [comment] 2014-04-04 21:22
Thanks @Scotchester!!
