### ISSUE TITLE
Update Display Header (for web) to Regular 

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#297] opened 2015-04-01 17:35 UTC
In order to better match the weight of our type hierarchy, I propose updating the Design Manual to change our Display header from Demi Bold to Regular. Currently, the only use case for the Display header is in hero graphics and Regular is the standard there. 
_(note: there are heroes that use H1 instead of Display but I'll post another issue to discuss heroes more specifically)._ 

![screen shot 2015-04-01 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/6887128/6947162/594a2de8-d873-11e4-9f4f-ab5f237a2a09.png)

**Comment by duelj** [comment] 2015-04-02 16:12
My impression was that the display heading was intended to be used where there where small amounts of copy that we really wanted to emphasize, and the demi does that quite well. I do agree that it feels like it stand out from the rest of the lighter type hierarchy but I think if we pull it all the way back to regular, it loses some of that extra "punch" and is a lot more similar to H1-3. I wonder if a medium weight (like used in h4) might be a nice in between? It would also be interesting to see the difference between the proposed regular wight display and and H1 as the title.

**Comment by nataliafitzgerald** [comment] 2015-04-02 17:28
@duelj - Here's a comparison of Regular, Medium, and Demibold. My thought is that the Display header is so large on the page that just the size gives it enough weight. We can certainly consider medium as an alternative, though. 

![screen shot 2015-04-02 at 1 21 56 pm](https://cloud.githubusercontent.com/assets/6887128/6969269/4373a918-d93b-11e4-855a-a0a120de9651.png)

With that being said, I am in the process of doing a full sweep of our current heroes (in our work that is live) and we are rarely even using the Display level in heroes (because of it's size - and, I suspect, our longer headlines). We are oftentimes using H1. Here are two instances of the Display header in demi bold on our existing web pages: 

![screen shot 2015-04-02 at 1 24 43 pm](https://cloud.githubusercontent.com/assets/6887128/6969336/d36dcde6-d93b-11e4-9ebc-73127f86a52b.png)
![screen shot 2015-04-02 at 1 24 14 pm](https://cloud.githubusercontent.com/assets/6887128/6969337/d370750a-d93b-11e4-9243-f4cfb1dedf00.png)

**Comment by duelj** [comment] 2015-04-02 18:02
Just to try and add some comparison I tried the three weights in browser (good call @ajbush) to see how they felt on the beta landing hero. I think the medium is my favorite from the couple examples I have seen, it has a bit of extra "bulk" but feels more inline with the other type weights. 

| regular | medium | demi |
| --- | --- | --- |
| ![screen shot 2015-04-02 at 1 57 14 pm](https://cloud.githubusercontent.com/assets/6873734/6970003/ae20bb70-d940-11e4-8b0c-887b74353d04.png) | ![screen shot 2015-04-02 at 1 57 32 pm](https://cloud.githubusercontent.com/assets/6873734/6970006/b5a5e3b6-d940-11e4-93b3-9fda31d518d5.png) | ![screen shot 2015-04-02 at 2 01 25 pm](https://cloud.githubusercontent.com/assets/6873734/6970021/cc44d99c-d940-11e4-92c9-a025785aacba.png) |

**Comment by ajbush** [comment] 2015-04-02 18:09
I think Demi has been kinda too big to use for our past content needs and have found it more useful for social media graphics and infographics, etc. 

But in the 3 options @duelj showed I would vote for medium. Especially if another situation arises like this Beta page where there's a heavy amount of illustration to compete with.

**Comment by nataliafitzgerald** [comment] 2015-04-02 18:18
@mebates - Do you find that you are using the display header in social media graphics? If so, can you share some use cases?

**Comment by mebates** [comment] 2015-04-02 18:39
I like the Medium too.

We don't use the H1 in standard social graphics, or Demi. The standard is an in-between 42 px regular, which you can see on the template on Drive. It has been used inconsistently across the larger infographics, so I don't think we can glean a standard from them.

http://files.consumerfinance.gov/f/2015_0113_mortgage_shopping_infographic.png
http://files.consumerfinance.gov/f/201304_cfpb_PaydayLoans_infographic1.png
http://files.consumerfinance.gov/f/blog_auto_loan.png
http://files.consumerfinance.gov/f/2014_0721_3years_infographic.jpg

**Comment by ajbush** [comment] 2015-04-02 18:50
Also, wanted to compare the weights when there's no illustration to compete with just like @duelj did with the Beta page. In this case regular seems fine but choosing a middle ground like medium could be better for trying to create a standard that could work with both heavy illustration and little to no illustration in the hero space.

| regular | medium | demi |
| --- | --- | --- |
| ![1](https://cloud.githubusercontent.com/assets/6931351/6970954/0aca9a98-d947-11e4-850b-0f4eb64606be.png) | ![2](https://cloud.githubusercontent.com/assets/6931351/6970958/10b25cde-d947-11e4-9752-a1aa23e46f82.png) | ![3](https://cloud.githubusercontent.com/assets/6931351/6970961/163ad564-d947-11e4-81de-4fd54c48c6d4.png) |

**Comment by nataliafitzgerald** [comment] 2015-04-02 19:24
@ajbush - In the "Submit a Complaint" example I actually don't think that regular works. This hero is not a good use case because of the textured background, something that is not within our current standard. 

I don't feel that the number of objects in the flapjack beta page are a good gauge for the header weight, considering that there are many more objects in that layout than we would typically include (i.e. this page is an anomaly and a one-off/singular by its very nature - and is meant to look different than our other web pages and products).

I mocked this up this comparison with some other examples that are more in lines with the type of illustrations we typically include in heroes (of course this is not a full representation but it gives the idea). In these examples I prefer the Regular weight for Display in these examples. 

![screen shot 2015-04-02 at 3 17 05 pm](https://cloud.githubusercontent.com/assets/6887128/6971573/6e79701a-d94b-11e4-9c97-cd8760ac53e0.png)

**Comment by nataliafitzgerald** [comment] 2015-04-02 19:42
It sounds like we still need to identify actual use cases (on the web) for Display. It sounds like we are infrequently using it at the hero level (this could change if we start to develop a more formal hero hierarchy). In social graphics, it sounds like we are using it at a smaller size 42 pixels. So this brings up additional questions and perhaps a need for further testing. It sounds like we're all in agreement that the demi bold is to heavy for our current style.

**Comment by ajbush** [comment] 2015-04-02 20:08
Ok I change my vote haha. In those examples the medium looks a little heavy.

But I do feel like medium is rendered differently (lighter) in browser than inside of .ai...but that's probably being too nitpicky.

**Comment by nataliafitzgerald** [comment] 2015-04-27 19:50
If Medium is rendered differently do we have a way to test out these two options (Medium versus Demi-Bold) in browser in order to make a call? If we're going based on Ai. I prefer the Regular.

**Comment by caheberer** [comment] 2015-04-28 13:20
I agree that I like the Regular when seen in AI. The spacing between the header and the paragraph provide enough separation for the hierarchy to make sense.

**Comment by Dnpizarro** [comment] 2015-05-04 16:32
+1 on the Regular.

**Comment by stephanieosan** [comment] 2015-06-01 14:39
I played around in the browser dev tools to get these screenshots:

| Demi | Medium | regular |
| --- | --- | --- |
| ![screen shot 2015-06-01 at 10 37 18 am](https://cloud.githubusercontent.com/assets/6433178/7915297/957feb2a-084a-11e5-9d00-5c4f006f122d.png) | ![screen shot 2015-06-01 at 10 38 31 am](https://cloud.githubusercontent.com/assets/6433178/7915309/a658b350-084a-11e5-9457-99f31db6e858.png) | ![screen shot 2015-06-01 at 10 38 52 am](https://cloud.githubusercontent.com/assets/6433178/7915318/afcf3c2e-084a-11e5-8afb-66eb51802ad6.png) |

**Comment by Dnpizarro** [comment] 2015-06-01 18:03
@stephanieosan where you referring to taking on this issue? I'm not assigning this to you but I know you mentioned it towards the end of the DM meeting.

**Comment by stephanieosan** [comment] 2015-06-01 19:18
I meant this one #301, but this one is related, so I'm happy to push this along, too!

**Comment by Dnpizarro** [comment] 2015-06-01 21:12
Awesome! Thanks for talking these on @stephanieosan .

**Comment by mebates** [comment] 2015-06-23 14:41
Hey @stephanieosan! Our Design Manual monthly is on 6/29. Think we can get this issue closed out by then?

**Comment by stephanieosan** [comment] 2015-06-23 20:25
It seems like the majority of folks who weighed in favored the Display to change to Regular. Any objections or changes of opinion after I posted the screenshots from the browser? If not, I think this is decided.

**Comment by mebates** [comment] 2015-06-29 17:13
@nataliafitzgerald we need you approval to move forward.

**Comment by nataliafitzgerald** [comment] 2015-06-29 17:36
Approved.

**Comment by mebates** [comment] 2015-07-08 16:52
- [ ] Add to the Design Manual
- [ ] Update Capital Framework
- [ ] Update .ai template(s) to reflect new standard

**Closed as completed** 2015-11-13 17:02 UTC

**Comment by nataliafitzgerald** [comment] 2015-11-13 17:04
Remaining task: Update our graphic design web templates to reflect this change. Putting this on the radar @duelj @ajbush @mebates @Dnpizarro
