### ISSUE TITLE
PDF interaction

### ISSUE THREAD

**Issue by juidai** [cfpb/design-manual#294] opened 2015-03-26 16:03 UTC
CF.GOV have many PDF documents. We would like to handle the interaction in the same way. There are two interaction method and we would like to get feedback.
1. Load PDF into a new window/tab
2. Load PDF in the same window  
   Discuss…

**Comment by Scotchester** [comment] 2015-03-26 18:20
I feel that people probably expect these to open in new tabs. I think viewing a PDF is more or less equated with a download, even if it can be done in-browser.

**Comment by benguhin** [comment] 2015-05-04 15:25
I think they should load in the same window, with two assumptions:
1. If a user _wants_ the link to open in a new window, they will be fully capable of making that happen for themselves
2. If a user just wants to see the thing, they don't want it to open in a new window

Additionally, I've heard that older users and other folks who don't use the web very often get confused when links open in new windows. I haven't observed this myself, but it's something we can follow up on.

You will be able to find dozens articles arguing for either side, but here's one that argues against opening links in new windows: http://www.smashingmagazine.com/2008/07/01/should-links-open-in-new-windows/ 

@JenniferHoran do you have a recommendation in terms of accessibility?

**Comment by JenniferHoran** [comment] 2015-05-04 16:39
It is great to make it clear where to click/select to open in a new window or download the PDF, often when you use assistive technology it can get funky trying to navigate a PDF in a browser and the PDF does better in its native environment, so you want to be able to download it and save it somewhere on your computer. Advanced AT users know this. I don't want to confuse older users and those who don't use the web very often. Let's set it up as you suggest above and see what kinds of feedback we get from users? And how is this being presented for mobile device users, I'm just wondering?

Excel has an even worse problem, it is always best in its native environment vs in a browser for AT. PPTs that automatically launch as a slideshow in a browser, as well.

**Comment by Dnpizarro** [comment] 2015-05-04 17:11
Can we add this to the links page in the Design Manual. @benguhin can you work on a mock up of this?

**Comment by JenniferHoran** [comment] 2015-05-04 17:12
I have my JAWS installed now FYIs so I can test for focus!

**Comment by mebates** [comment] 2015-05-07 19:03
The two PDF resources in Owning a Home currently open in the same window. Just FYI for anyone who wants to play with it! http://www.consumerfinance.gov/owning-a-home

**Comment by mebates** [comment] 2015-06-23 21:03
@benguhin did this get updated? I looked in the 'Links' section and didn't see the update. If so, please close this issue.

**Comment by benguhin** [comment] 2015-06-26 22:41
Yep it's merged in pull request #323 !

See it at https://cfpb.github.io/design-manual/ui-toolkit/links.html

**Closed as completed by benguhin** 2015-06-26 22:41 UTC
Labels: 1 - Working

**Comment by klocraft** [comment] 2015-09-03 19:05
We've made a few PDF discovers in the last weeks, which could have an impact on how we choose display PDFs on our website. @stephanieosan noted:

> I do want to let y'all know some trouble we've run into with the OaH Budgeting Worksheet recently—even though we were able to make the PDF do math for users when the PDF is open in Acrobat, if a user opens the PDF in the browser, the math doesn't work at all. We're having to force our budgeting worksheet to download so that users will open it locally instead of on the browser. 
> 
> None of this is ideal, since we can't guarantee that a user won't still open that downloaded file in a browser (and then be utterly frustrated). 

In a nut shell, if you create an interactive PDF (Forms or Worksheets with fillable fields, sections that auto calculate, use custom java, etc), the interaction does not always function when the PDF is viewed in a browser. The level of interaction seems to depend on the browser. If the viewer downloads the PDF views it in Acrobat, there is no issue and the PDF functions as intended. 

I know the issue is further complicated because, as @Scotchester points out:

> in recent versions of Chrome, if you download a PDF and then click the little downloaded file button at the bottom of the Chrome window to open it, it opens in Chrome! Soooo stupid. You have to open the download's menu and say "Open with system viewer" to avoid that behavior.

My question is: Are there 'best-practices' or other ways of providing our PDFs that could help ensure a PDF is downloaded so it can open in Acrobat? 

UXers, throwing this out there, but it might be a horrible idea. If there are specific reasons we prefer a 'view in browser', then what if we included 2 links for PDFs. One that says "Preview XYZ in browser" and one that says "Download XYZ". Then users would know there are 2 ways of viewing a PDF, and could sample the document before committing to a download.

Or, if we keep current interaction, then at least include a "warning" that 'previewing a PDF within a browser may limit its functionality. For best results, download and view with Acrobat.'

**Comment by JenniferHoran** [comment] 2015-09-03 19:28
My 2 cents, this also happens with Excel, if you open Excel in the browser you don't get the same interaction that you have in its native environment. Adobe PDF in a browser vs native environment is a known issue for 508, it is usually best not to rely on viewing in the browser. Not all end users realize this, though.
