### ISSUE TITLE
Merge HMDA API Docs HTML and CSS code with design-manual

### ISSUE THREAD

**Issue by danny8000** [cfpb/design-manual#23] opened 2014-02-11 18:41 UTC

**Comment by danny8000** [comment] 2014-02-11 19:48
I put a green border on the left side of the secondary nav element that represents the current page. 

I would like a designer to review the styling.

**Comment by danny8000** [comment] 2014-02-11 19:50
Note, you won't see these changes at this repo until I send a pull request. For now you can view the pages here:

http://danny8000.github.io/design-manual/guides/design-best-practices.html

**Comment by mebates** [comment] 2014-02-11 19:58
The bevel at the bottom of the green line is pretty pronounced. 
Can the menu design match the menu here (row height, type, etc): http://cfpb.github.io/api/hmda/?

Thanks for clarifying these issues!

**Comment by Scotchester** [comment] 2014-02-11 20:01
Having the bottom border be 2px wide and lighter in color than the page you referenced, @mebates, is what was making the bevel (caused by the joining of the left and bottom borders) more pronounced.

I agree with making it match the HMDA API docs menu.

**Comment by danny8000** [comment] 2014-02-11 20:51
The HMDA API docs design is very polished. Why didn't we just use the HTML and CSS from that project as a starting point for this project?

**Comment by mebates** [comment] 2014-02-11 20:54
I don't know, maybe @davidakennedy can elaborate. I thought we WERE basing it on DOCter, which I think the HMDA API thing was either based or DOCter was built from.

**Comment by dezzie** [comment] 2014-02-11 20:56
Since I coded it, it may look good, but it's kind of a hot mess inside.
![ackbar](https://f.cloud.github.com/assets/1301932/2141987/fee481f0-935e-11e3-8f60-660d7c6d28de.gif)

**Comment by danny8000** [comment] 2014-02-11 20:58
Ok, I will do a little bit of research, maybe the API docs have evolved away from DOCter.

**Comment by dezzie** [comment] 2014-02-11 21:00
HMDA docs branched away from DOCter early on when it was newly hatched to document eregs stuff; @ascott1 and I were working on our stuff in tandem. Lemme know if you're trying to look for something specific!

**Comment by danny8000** [comment] 2014-02-11 21:18
Dave started with DOCter, so this repo does not reflect any of your code. I plan to merge all of the relevent HTML/CSS code in from API docs into the design-manual, hopefully tomorrow. 
(Then maybe I will update DOCter once the design manual is complete so there is a up-to-date repo for starting new projects.)

**Comment by ascott1** [comment] 2014-02-12 12:24
Pull requests to DOCter are welcome! It was a 1 day project based on the eRegs docs. :smiley:

**Comment by dezzie** [comment] 2014-02-12 16:20
Merging in the CSS and responsive bits from HMDA docs would be great for DOCter. I'll be forking you @danny8000!

**Comment by iuloshi** [comment] 2014-02-12 17:08
:+1:

**Comment by danny8000** [comment] 2014-02-12 17:35
I updated this issue's name to be more desriptive.

**Comment by ascott1** [comment] 2014-03-26 01:30
Should this issue move to the DOCter repo?

**Comment by Scotchester** [comment] 2014-03-26 01:37
Yeah, probably. I'm intending to do this when I set up the build branch.

**Comment by ascott1** [comment] 2014-03-26 01:52
Created the issue in the DOCter repo and closing this one.

**Closed as completed by ascott1** 2014-03-26 01:52 UTC
