### ISSUE TITLE
Add modals to the Design Manual

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-manual#325] opened 2015-06-01 20:26 UTC
- [ ] edit content
- [ ] design pages
- [ ] develop visuals or link to Capital Framework code (if it exists)

**Comment by benguhin** [comment] 2015-07-31 22:21
There are a few issues that @himedlooff raised in our internal repos that our worth checking out for this. It may be best to avoid using modals wherever possible because (1) they're hard to control across different browsers and devices and (2) you can usually get what you're looking for from an expandable section or a separate page.

**Comment by kurzn** [comment] 2016-04-01 16:35
@stephanieosan can we close this issue? I think it's a duplicate of #231

**Closed as completed** 2016-06-13 15:02 UTC
Labels: 1 - Working
